import Head from 'next/head'

const Index = () => {

  return (
    <div>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Next.jsで学ぶReact講座</h1>
      <p>APIを色々叩く！</p>
    </div>
  );
};

export default Index;